### PR TITLE
Fixed some things

### PR DESCRIPTION
**Pull request by Sollace**
Now that I'm able to do some tests I've gone through fixing some things. Got my test mod updated and working and tried two things:
1. Adding a brand new block
2. Replacing an existing block

Of course neither worked correctly so I've had to make some changes to fix that. It turns out there is a little bit of setup to do after adding a block to the registry. The same goes for item-blocks.

To replace an existing block there turned out to be a not-so-little bit of stuff that has to be done. In addition to what has to be done after putting it in the registry I had to remap all the blockstates for the old block onto the new one and remap the model from the old one as well.

I've also expanded on the apis a little to include support for block and item rendering, and I've added a thing to register names for a block/item's variants.

So now adding a new block should look something like this:

        Block test = new TestBlock(Material.carpet, "test_block");
    	ApiBlock.registerBlock(2000, "test_mod", "test_block", test);
    	ApiItem.registerItemBlock(test);

And here's the code I used that replaces grass blocks:

    	Block grass = new TestBlock(Material.carpet, "grass");
    	ApiBlock.replaceBlock(Blocks.grass, grass);
    	ApiItem.registerItemBlock(grass, new ItemColored(grass, false));

### CODE REVIEW

**Comment by warriordog** [comment]
Sweet, glad you could test that!  Do you think we should add a util method that combines the block and item registering, and maybe another for replacing?

**Comment by Sollace** [comment]
I don't think so. The idea did occur the me to have block registering combined with item block registering but I think it may be better to leave them separate and let the modder decide how they want do that.

Forge has them combined and it was a nightmare for me to figure out how to get it to register without an itemblock so I could use my own items for them.

**Comment by warriordog** [comment]
@Sollace 

I meant like a separate method that could be used if you wanted to do both.  You wouldn't have to use it, but you could if you wanted.

**Comment by Sollace** [comment]
@warriordog 
Sure, I suppose we could do that. Would it go in ApiBlock?

**Comment by Sollace** [comment]
@warriordog 
Ok, I'll put it into my next PR if it hasn't been included yet.

**Pull request merged**
