### PR TITLE
A few changes

### PR DESCRIPTION
**Pull request by Sollace**
Added some more docs and adjusted the InventoryListener events.
Improved UpdateType, and implemented IStringable.

Also does anyone read the todos I leave in here? I specifically put them there for things I don't know how to do in hopes that someone who does can pick them up.

### CODE REVIEW

**Comment by warriordog** [comment]
I'm not ignoring this, I just keep forgetting to look at this when I'm at
my pc.

**Comment by Sollace** [comment]
@warriordog 
Sorry, have I PR'd these before?

I pushed two more commits yesterday and didn't remember ever open a request for the previous stuff. Didn't know I even had commits still out until I checked yesterday. :/

Unless you mean the TODOs, then that's fine. You can look at them when you can, I just don't want them to go undone forever.

**Comment by warriordog** [comment]
I mean the whole PR.  I've been hosting a planning meeting and haven't been
able to sit down and look at this yet.  I haven't even read the commit
titles yet, lol.

**Comment by warriordog** [comment]
I merged from my phone, when I'm at pc I will look through to find todos.  Also consider putting unfinished stuff in a different branch, so people know it isn't done.

**Comment by Sollace** [comment]
@warriordog 
"Also consider putting unfinished stuff in a different branch,"
How would that work?

I can make different branches for unfinished stuff but then you wouldn't get it unless I make a PR for each branch.

Some of the stuff's been in there for ages anyway, like the ParticleRegistry that works but needs a packet channel to send and receive custom particles.

**Comment by warriordog** [comment]
You could make a PR to a "WIP-<whatever>" branch with the code, then ask for help with that.

**Pull request merged**
