### PR TITLE
And here's the other stuff

### PR DESCRIPTION
**Pull request by Sollace**
I decided to put these last three into their own PR to look at them individually.

Three new classes:
JSArrayUtils
Implements most of the array features found in javascript plus a few other small utilities. They can come in very handy at times.

Any methods not included in there can probably be found in org.apache.commons.lang3.ArrayUtils.ArrayUtils.

__Options__
Something from Functional Programming to indicate a value or lack there of.
A function that returns Option can have only two values:
None
Some x
Where x is any value.

__Tuple__
May have gotten a bit carried away with this one.
A generic alternative to minecraft.util.Tuple that serves as an equivalent to C#'s Tuple. It supports tuples from 1-7 values, or more with some extra setting up.

It has a fair bit of replicated code but I was unable to find any better way of implementing the functionality in Java.

### CODE REVIEW

**Comment by warriordog** [comment]
Java 8 already has an Option class, and soon MC will require java 8 so we will be able to use that.

**Comment by Sollace** [comment]
@warriordog 
Ok, I'll find it and switch to that.

**Comment by Sollace** [comment]
@warriordog 
I can't find it.
The closest I see is Optional: http://www.oracle.com/technetwork/articles/java/java8-optional-2175753.html

But the syntax they have for that is kind of weird.

**Comment by warriordog** [comment]
Oops that is what I was thinking of, but it does the same thing.

**Comment by Sollace** [comment]
:c *clutches onto his scrap of dearly scribbled code*

I will remove it then.

**Comment by warriordog** [comment]
Looks, good, but in the future watch what classes you import.  JSArrayUtils uses a class from JavaFX, which is not available on "server" JRE builds.  And starting in java9 JREs will be configured by application, so MC will likely run without a lot of extra java libraries like javaFX.

**Comment by Sollace** [comment]
All right. I didn't know about that.

I can replace it with something else.

**Comment by Sollace** [comment]
"java.util.function.Function" is pretty much equivalent. Shall I PR the change?

**Comment by warriordog** [comment]
Sure, better to do it now so we don't forget.

**Pull request merged**
