### PR TITLE
So yeah, I did a bunch of stuff...

### PR DESCRIPTION
**Pull request by Sollace**
First thing is I updated the bl_at.cfg. I commented out some items that are no longer needed in 1.8 and added some others for consistency.

I've updated ApiGui, the old method is not depricated and won't do anything. The new one has been based off of the code for chests and should work correctly.

Lastly I reimplemented 'BLCraftingManager' as ApiCrafting. That needed a rewrite anyway.

There's only one catch though, I wasn't able to test anything. I don't know what's wrong but I've got errors all over the place, some in BlazeLoader and a lot of others in LiteLoader. So until I can fix my MCP I'm working blind.

I also have no idea how you get it to apply it's changes/hooks to the minecraft source. :f

### CODE REVIEW

**Comment by warriordog** [comment]
I'll pull this into my fork and try it.  The way to set up MCP is to change  the update URL to liteloader, then manually apply the blat.cfg

**Comment by warriordog** [comment]
I'll pull this into my fork and try it.  The way to set up MCP is to change  the update URL to liteloader, then manually apply the blat.cfg

**Comment by warriordog** [comment]
Huh comment posted twice...

**Comment by Sollace** [comment]
Yeah, I did both of those. Unless I somehow have the wrong liteloader version.

Most of the errors in Blazeloader seem to be coming from COMCore. It can't find MathUtils where it's looking and there isn't any ELogger, just a CLogger.

**Comment by warriordog** [comment]
CompCore?  Download a new version from my repo.

**Comment by Sollace** [comment]
@warriordog 
I found what the problem is. Blazeloader is still using an extremely old version of CompCore os of course it's going to throw a fit when I try to use it with the one pulled directly from your repo.

**Comment by warriordog** [comment]
Huh, that's odd.  I will fix it when I am back to PC.  Also could you check
that this repo and mine are equal?

**Comment by warriordog** [comment]
@Sollace 

Yeah so I found the problem, this repo was three commits behind mine.  I merged them in, but now your PR will probably have merge conflicts...

**Comment by Sollace** [comment]
> Huh, that's odd. I will fix it when I am back to PC. Also could you check that this repo and mine are equal?
They should be equal. I'm not creating a fork of CompCore, just git cloning it to my desktop since I don't plan on editing it.

**Comment by Sollace** [comment]
*bump*

I hope no one's forgotten about this. I can't carry on with any thing else until this is merged or tossed out.

**Comment by warriordog** [comment]
Merged

**Comment by Sollace** [comment]
Thank you, I'll move on to the repackaging next.

Might have some other changes but those can come separately.

**Comment by warriordog** [comment]
@sollace
Cool, if I don't notice one then mention me in a comment

**Pull request merged**
