### PR TITLE
Working 2

### PR DESCRIPTION
**Pull request by Sollace**
Everything I've done in the past week.

Changes:
 - Updated version files
 - Added a 1.8.json
 - Cleaned up the event injection transformers and updated the handler locations to match the package structure
 - Changed ApiBlock and ApiItem to use liteloader's native methods
 - Updated BLMain.getCommandHandler to return the correct type for the client
 - Fixed BlazeLoaderCP.onPostInit registration of the internal resourcepack (mighthave to update LiteLoader if you get errors with this)
 - Updated documentation and depricated OverrideEventClientHandler.overrideSpawnParticle

Additions:
 - Added ApiParticles. I wasn't sure about including this since it's a big addition and certain parts are not completed (check for TODOs). It comes with an implementation of shapes which may or may not be redundant, they're used to pick random points in inside their bounds for spawning particles. I'm also still stuck in this situation where I can't test anything, the game compiles and starts, and LiteLoader is these but BlazeLoader doesn't run at all. :c

Also if you do end up updating liteloader note that you will find one or two errors in Liteloader. You just have to find them and change the method names to match the deobfuscated ones.

@warriordog *poke*

### CODE REVIEW

**Comment by warriordog** [comment]
@Sollace 
Apparently we are using different versions of MCP, because you have lots of references to deobfuscated methods and fields that are still obfuscated in my code.

**Comment by Sollace** [comment]
@warriordog 
I'm actually using the mappings Mumphry provides for working with Liteloader. It's possible that they were updated since you set up your environment.

**Comment by warriordog** [comment]
Probably so.  I think I will make a new BL dev env to make sure there are
no other issues

**Comment by warriordog** [comment]
Oh sorry @Sollace, I completely forgot about this!  I will try to get a new LL environment set up and then see about merging it

**Comment by Sollace** [comment]
@warriordog
Ah, thanks. I've been away for a bit but I think once you have this one merged I can put up one more. I found your Wall class and have been fiddling with it a little. [linky](https://github.com/Sollace/BlazeLoader/blob/WallUpgrade/src/com/blazeloader/api/compatibility/Wall.java)

**Comment by warriordog** [comment]
@sollace nice, I have been wanting to make some improvements to the wall
but haven't had any ideas!  I hope to be finished setting up new BL dev by
this afternoon, so I can test the changes

**Comment by warriordog** [comment]
@Sollace 

Even with newest MCP there are lots of uncompilable names in BL.  About half of the changes you made have names that are still func_xx in MCP.  Where did you get your MCP download, and did you do anything to it?

**Comment by Sollace** [comment]
@warriordog 
My MCPVersion is 9.10.

Did you remember to apply the mappings from the Liteloader site?

I believe in /conf/mcp.cfg you have to change UpdateUrl to:
http://dl.liteloader.com/files/mcprolling_{version}/ 
And then run updatemcp.bat and re-decompile minecraft.

For some reason I'm getting a permission denied error when I check for updates so if you get that just let me know and I can send you the mappings files from mine.

**Comment by warriordog** [comment]
@Sollace 

The guide to install LL no longer says to use the other repo.  I checked the quick start guide and tutorial and both say to just use plain MCP.  https://www.assembla.com/spaces/liteloader/wiki/Quick_Start_Guide_-_for_advanced_users

**Comment by Sollace** [comment]
@warriordog Hm...

I followed what the README.md inlcuded in the repo said:

LiteLoader
----------

Important Setup Note
--------------------
MCP 9.10 does not include the latest MCPBot mappings, since developing mods without these updated
mappings is a massive nuisance LiteLoader is built using a recent snapshot of the MCP mappings.

The latest MCPTEST mappings can always be retrieved from [http://mcpbot.bspk.rs/testcsv/](http://mcpbot.bspk.rs/testcsv/) 

Getting the updated mappings
----------------------------

To get the updated mappings, perform these steps **before** decompiling minecraft for the first 
time. If you have already decompiled minecraft, run the MPC **cleanup** task first to remove the
invalid sources, or simply delete the *temp* and *src* directories from your MCP installation.

-   Using a text editor, open **/mcp910/conf/mcp.cfg**
-   Locate the setting **UpdateUrl** and change the domain to *dl.liteloader.com* as shown

    UpdateUrl         = http://dl.liteloader.com/files/mcprolling_{version}/

-   Save the file and run the **updatemcp** script, it should prompt you to download 3 files.
-   Type **yes** to accept the download. 
-   Run **decompile** as normal.

I suppose you can try using the mappings from MCPTest. If that doesn't work then I suppose I'll have to go change my one to match mcp's latest mappings.

**Comment by warriordog** [comment]
Ooh I didn't do that, I need to tell my mumfrey that his instructions are
missing steps

**Comment by Sollace** [comment]
@warriordog That would be good. Perhaps just say to look at the readme during the MCP setup step for special instructions. Since that will probably change between versions.

**Comment by warriordog** [comment]
@Sollace 

Yeah I will cleanup and fix MCP this afternoon, then try again.

**Comment by warriordog** [comment]
@Sollace 

I used the fixed MCP and got this working, I will pull this followed shortly by another commit that fixes a couple compile and runtime issues.

**Comment by Sollace** [comment]
@warriordog Welp. It seems I have to fix my mcp now. Your mappings are newer than mine.

Can you link me to where you got them?

**Comment by Sollace** [comment]
@warriordog 
Ok I'v got it sorted out but I still can't run BlazeLoader. LiteLoader just isn't detecting it.

**Comment by warriordog** [comment]
@sollace

You need to add a -api program argument, I will copy the exact one when I
am on PC.

**Comment by warriordog** [comment]
@Sollace 

Add "--api com.blazeloader.bl.main.BlazeLoaderAPI" (without quotes) to your program run arguments (make sure it is program and not JVM) and then see if it works.  If you already have it make sure you have changed the class name to match the new package structure.

**Comment by Sollace** [comment]
@warriordog 
Thanks, that's fixed it.

**Comment by warriordog** [comment]
@Sweet, tell me if you run into any more problems!

**Pull request merged**
