### PR TITLE
Improved the Wall

### PR DESCRIPTION
**Pull request by Sollace**
I also cleaned up a bunch of the docs (I just recently found I can use html tags in there), moved some methods from ApiBlock to ApiWorld where they fit in better, and made some minor additions to the api.

I also implemented the previously extremely broken NotificationType.

### CODE REVIEW

**Comment by warriordog** [comment]
Sweet, I've been meaning to fix the NotificationType but I keep forgetting to actually go and do it :)
But why did you use "I" as the generic type for the wall?  "T" is the java standard for a non-specific generic type.

**Comment by Sollace** [comment]
@warriordog 
I'm... not sure actually. If you look through all those related classes you might find they all use I. I think I picked it initially because you have "Items" on the wall. The I stood for Item but then it sort of stuck.

The I looks a bit nicer than a T if you ask me, but I suppose you can change it.

**Comment by warriordog** [comment]
I'll probably leave it for now since it doesn't hurt, but later on I may change it since "T" is a bit more visible than "I" in a lot of fonts.

**Comment by Sollace** [comment]
Yeah, I see that from the font on here.

**Pull request merged**
