### PR TITLE
Getting things to work

### PR DESCRIPTION
**Pull request by Sollace**
All (implemented) events now function correctly and mods are registered to them when they implement the right interfaces. The package structure has also been altered slightly to better distinguish between EventHandlers, and EventListeners.

I've finally gotten entity events working. There is now an event for when an entity is constructed and you can register a property object that receives events when the entity saves/loads nbt or is initialised.

Also so people know:
I had trouble getting it to register an event for a constructor. It turns out the BLOBF doesn't recognise constructor signatures when you give them to it so I had to create a method of registering to a constructor.

There's also a bug with LiteLoader where ModUtilities.addBlock generates an exception. It's only a minor issue but I thought I'd mention it. It happens because it mistakes the AirBlock instance that the registry returns in the case of a block not being registered for a block that's actually registered and tries to replace Blocks.air with the block you've given it.

### CODE REVIEW

**Comment by warriordog** [comment]
You may want to report that bug to mumfrey, if you see him on IRC.  That is something he will want to fix.

**Comment by Sollace** [comment]
@warriordog 
I figured I should, but I'm not often on IRC. Might put it in the thread on MCF though.

**Comment by warriordog** [comment]
@Sollace 

You forgot to include BlazeLoaderIP, and now my fork is in shambles...

**Comment by warriordog** [comment]
@Sollace 

Ah crap nvm, my merge failed halfway through.  Now I lost the code I spent all day working on :(

**Comment by Sollace** [comment]
@warriordog 
:c

To avoid that problem you should only work on a branch, never the master. Then you can merge into main and, commit whatever changes you have, and rebase your branch back on top of master fixing conflicts as they arise. It also helps keep the history nice and clean.

[git stash](http://fav.me/d7e4h8a) is also a useful command.

**Pull request merged**
